spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: nhan
    password: 123456
  jpa:
    database: mysql
    show-sql: true

application:
  security:
    jwt:
      secret-key: dba9dc7401fbe88660e4d65aad0cb90dbb423509c6cafe2ae4fbfd56fd99e6d5
      expiration: 60 # a minute
      refresh-token:
        expiration: 604800000 # 7 days

