spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: nhan
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 183579654844-qlnsl2utm5jje30v9mibvn6u1o36ked8.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/api/v1/auth/oauth2/google
            scope:
              - email
              - profile
        provider:
            google:
                authorization-uri: https://accounts.google.com/o/oauth2/auth
                token-uri: https://accounts.google.com/o/oauth2/token
                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                user-name-attribute: sub

application:
  security:
    jwt:
      secret-key: dba9dc7401fbe88660e4d65aad0cb90dbb423509c6cafe2ae4fbfd56fd99e6d5
      expiration: 60 # a minute
      refresh-token:
        expiration: 604800000 # 7 days

