@userToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaGEyIiwiaWF0IjoxNzIzMDg2MjMwLCJleHAiOjE3MjM2OTEwMzB9.Y4i9pnnz3ognrVg7EThk8y-YzC19cH7g0PlcmReWyVVhvAQAqh0fxcRwoi9hUmXV2TP17Sviz43rK1-6sqIMAg
@adminToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaGEyIiwiaWF0IjoxNzIzMDg2MjMwLCJleHAiOjE3MjM2OTEwMzB9.Y4i9pnnz3ognrVg7EThk8y-YzC19cH7g0PlcmReWyVVhvAQAqh0fxcRwoi9hUmXV2TP17Sviz43rK1-6sqIMAg
@expiredToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaGFuIiwiaWF0IjoxNzE5NjU4NDE0LCJleHAiOjE3MTk2NTg0MTR9.FTmgu3OXLSJ43PgBrtSxZ5giRCOepyCO9e4aGLdQ9n1GXwoIvcbPpZpW4unED581f5Yl6lsxLmOjy1PJt3wupw

### Sign up
POST http://localhost:8080/api/v1/auth/sign-up
Content-Type: application/json

{
  "password": "1256",
  "email": "nhaan92@gmail.com",
  "firstName": "nhan",
  "lastName": "nguyen",
  "username": "nha2"
}

### Login - admin
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "nhakk",
  "password": "12456"
}

### Expired token
GET http://localhost:8080/security
Authorization: Bearer {{expiredToken}}

<> 2024-06-29T180329.401.txt

### No bearer token
GET http://localhost:8080/home

### True token
GET http://localhost:8080/security
Authorization: Bearer {{userToken}}

### FAKE TOKEN
GET http://localhost:8080/security
Authorization: Bearer nhannnguyen.asdbas.cewae

### ADMIN ROLE - allow
GET http://localhost:8080/api/v1/admin/secret
Authorization: Bearer {{adminToken}}

### ADMIN ROLE - not allow
GET http://localhost:8080/api/v1/admin/secret
Authorization: Bearer {{userToken}}

### Not found endpoint - admin role
GET http://localhost:8080/not-found
Authorization: Bearer {{adminToken}}

### No endpoint - white url
GET http://localhost:8080/api/v1/auth/not-found

### Change password
POST http://localhost:8080/api/v1/user/change-password
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "currentPassword": "123456",
  "newPassword": "1234567",
  "confirmationPassword": "1234567"
}

### Log out
GET http://localhost:8080/api/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaGFubmd1eWVuIiwiaWF0IjoxNzE5NjcwNzI5LCJleHAiOjE3MjAyNzU1Mjl9.bAZgV7rmuErmkEWmal3HtCh5nhPpsLJv41qnBjHIlI096a7mbXVXcNA192aA1hgV7Ko_wCpNnJ_DaJIS76hVAw

###Refresh token
POST http://localhost:8080/api/v1/auth/refresh-token
Authorization: Bearer {{userToken}}

### Login - user
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "nha",
  "password": "123456"
}


