###Get all books - default page 0 and size 10
GET http://localhost:8080/api/v1/book
Authorization: Bearer {{userToken}}

###Get all books - page 1 and size 5
GET http://localhost:8080/api/v1/book?page=1.5&size=5
Authorization: Bearer {{adminToken}}

###Get all books - category = 1
GET http://localhost:8080/api/v1/book?page=0&filter=category.id=1
Authorization: Bearer {{adminToken}}

### Create a new book - invalid category id
POST http://localhost:8080/api/v1/book
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "title": "Book NEW",
    "author": "Author NEW",
    "price": 100.0,
    "published_year": "2021",
    "publisher": "Publisher NEW",
    "category": {
        "id": 100
    }
}

### Create a new book
POST http://localhost:8080/api/v1/book
Authorization: Bearer {{adminToken}}
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="book"
Content-Type: application/json

{
    "title": "Book NEW",
    "author": "Author NEW",
    "price": 100.0,
    "published_year": "2021",
    "publisher": "Publisher NEW",
    "category": {
        "id": 1
    }
}

--boundary
Content-Disposition: form-data; name="bookImage"; filename="avatar1.jpg"
Content-Type: image/jpeg

< /home/nhan/Downloads/21120514_055/source/public/game_avatar/avatar1.jpg

--boundary--

### Create a new book - forbidden
POST http://localhost:8080/api/v1/book
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
    "title": "Book NEW",
    "author": "Author NEW",
    "price": 100.0,
    "published_year": "2021",
    "publisher": "Publisher NEW",
    "category": {
        "id": 1
    }
}

### Update a book by id - 1
PUT http://localhost:8080/api/v1/book/1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "title": "Book NEW",
  "author": "Author NEW",
  "price": 100.0,
  "published_year": "2021",
  "publisher": "Publisher NEW",
  "category": {
    "id": 1
  }
}

### Create a new book - invalid category id
POST http://localhost:8080/api/v1/book
Authorization: Bearer {{adminToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data, name = "book"
Content-Type: application/json

{
    "title": "Book NEW UPDATED",
    "author": "Author NEW UPDATED",
    "price": 100.0,
    "published_year": "2021",
    "publisher": "Publisher NEW",
    "category": {
        "id": 1
    }
}
--boundary

### Update a book by id - 100 (no data)
PUT http://localhost:8080/api/v1/book/100
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "id": 100,
    "title": "Book UPDATED",
    "author": "Author UPDATED",
    "price": 100.0,
    "published_year": "2021",
    "publisher": "Publisher UPDATED",
    "category": {
        "id": 1
    }
}

###Delete a book by id - 10
DELETE localhost:8080/api/v1/book/10
Authorization: Bearer {{adminToken}}
