###Get all order - forbidden
GET http://localhost:8080/api/v1/order
Authorization: Bearer {{userToken}}

###Get all order
GET http://localhost:8080/api/v1/order
Authorization: Bearer {{adminToken}}

###Create a cart
POST http://localhost:8080/api/v1/order/me/cart
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "shippingAddress": "1234 Main St",
  "orderDetails": [
    {
      "book": {
        "id": 13
      },
      "quantity": 8
    },
    {
      "book": {
        "id": 74
      },
      "quantity": 2
    }
  ]
}

###Update order by status
PUT http://localhost:8080/api/v1/order/2/status
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "status": "SHIPPED"
}